import { KP, TLDR, TODOS, TR, fmt, type Meeting } from "./data";

// Plain transcript text (real segments, or the demo lines with HTML stripped).
export function buildTranscript(m: Meeting): string {
  if (m.transcript?.length) {
    return m.transcript.map((l) => `[${fmt(l.start)}] ${l.speaker}: ${l.text}`).join("\n");
  }
  return TR.map((t) => `${t.who}: ${stripHtml(t.said)}`).join("\n");
}

// Full meeting report as Markdown — summary, key points, next steps, transcript.
export function buildReport(m: Meeting): string {
  const out: string[] = [];
  out.push(`# ${m.title}`, "");
  out.push(`${m.day}, ${m.time} · ${m.dur} · ${m.who}`, "");

  out.push("## Summary", m.summary?.tldr ?? TLDR, "");

  out.push("## Key points");
  if (m.summary) {
    for (const k of m.summary.keyPoints) {
      out.push(`- [${fmt(k.start)}] ${k.text} — "${k.quote}" (${k.speaker})`);
    }
  } else {
    for (const k of KP) {
      out.push(`- [${k.ts}] ${k.txt} — "${k.q}" (${k.who})`);
    }
  }
  out.push("");

  out.push("## Next steps");
  for (const s of m.summary?.nextSteps ?? TODOS) out.push(`- ${s}`);
  out.push("");

  out.push("## Transcript", buildTranscript(m), "");
  out.push("—", "Generated by Tenet");
  return out.join("\n");
}

export function mimeExt(mime?: string): string {
  if (!mime) return "webm";
  if (mime.includes("webm")) return "webm";
  if (mime.includes("ogg")) return "ogg";
  if (mime.includes("mp4") || mime.includes("m4a")) return "m4a";
  if (mime.includes("mpeg") || mime.includes("mp3")) return "mp3";
  if (mime.includes("wav")) return "wav";
  return "webm";
}

export function safeName(s: string): string {
  return s.replace(/[^\wÀ-ɏЀ-ӿ .-]+/g, "").trim().replace(/\s+/g, "_") || "tenet-session";
}

function stripHtml(s: string): string {
  return s.replace(/<[^>]+>/g, "");
}
